# Generated by Django 2.2.10 on 2021-12-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Авторизация', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=255, verbose_name='название опроса')),
                ('description_poll', models.TextField(verbose_name='описание опроса')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='дата старта')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_test', models.TextField(max_length=255, verbose_name='текст вопроса')),
                ('question_type', models.CharField(choices=[('ответ текстом', 'ответ текстом'), ('ответ с выбором одного варианта', 'ответ с выбором одного варианта'), ('ответ с выбором нескольких вариантов', 'ответ с выбором нескольких вариантов')], default=('ответ текстом', 'ответ текстом'), max_length=50, verbose_name='тип вопроса ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='опросы пользователей.Poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ')),
                ('answer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Авторизация.Userauth')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='опросы пользователей.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
