# Generated by Django 2.2.10 on 2021-12-10 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userauth',
            fields=[
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=512, verbose_name='ФИО')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='токен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен пользователя',
                'verbose_name_plural': 'Токены пользователей',
            },
        ),
    ]
